version: "2.1"

services:
  ejbca:
    image: primekey/ejbca-ce
    hostname: cahostname
    container_name: mycontainer
    ports:
        - "80:8080"
        - "443:8443"
    volumes:
        - ./src/main/resources/scripts/:/opt/primekey/scripts
    command: bash -c "
      ./scripts/ejbca-configuration.sh &
      /opt/primekey/bin/start.sh
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -kI https://localhost:8443/ejbca/publicweb/healthcheck/ejbcahealth"]
      interval: 10s
      timeout: 3s
      retries: 9

  certservice:
    image: onap/org.onap.aaf.certservice.aaf-certservice-api:latest
    volumes:
      - ./helm/aaf-cert-service/resources/cmpServers.json:/etc/onap/aaf/certservice/cmpServers.json
    container_name: certservice
    ports:
      - "8080:8080"
    depends_on:
      ejbca:
        condition: service_healthy

